### ISSUE TITLE
ProxyPanel 对接 trojan 无法自动申请证书

### ISSUE THREAD

**Issue by Draco-china** [sprov065/soga#44]
设置自动申请证书时，不论dns或者http模式都会直接提示找不到证书

**Comment by sprov065** [comment]
大概率没配置好

**Comment by Draco-china** [comment]
> 大概率没配置好

使用docker-compose.yml配置的
配置文件
```
version: "3.7"
services:
  soga:
    image: sprov065/soga:latest
    restart: on-failure
    network_mode: host
    environment:
      type: proxypanel
      server_type: trojan
      api: webapi
      webapi_url: 
      webapi_mukey: 
      node_id: 1
      cert_domain: xxx.com
      cert_mode: http
      force_close_ssl: 'false'              # 填写 false 或 true 参数值时需要加引号
      forbidden_bit_torrent: 'true'         # 填写 false 或 true 参数值时需要加引号
```
v2ray下正常
